{% set name = "yake" %}
{% set version = "0.4.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 859f379ac49ca204a0bc1527217f937321e87b68287f81db9700fc1039fd529a

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - yake = yake.cli:keywords


requirements:
  host:
    - python {{ python_min }}
    - pip
    - pytest-runner
    - setuptools
  run:
    - python >={{ python_min }}
    - tabulate
    - click >=6.0
    - numpy
    - segtok
    - networkx
    - jellyfish

test:
  imports:
    - yake
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/LIAAD/yake
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: Single-document unsupervised keyword extraction
  description: |
    Unsupervised Approach for Automatic Keyword Extraction using Text Features.
    YAKE! is a light-weight unsupervised automatic keyword extraction method which rests 
    on text statistical features extracted from single documents to select the most important 
    keywords of a text. Our system does not need to be trained on a particular set of documents, 
    neither it depends on dictionaries, external-corpus, size of the text, language or domain. 
    To demonstrate the merits and the significance of our proposal, we compare it against ten 
    state-of-the-art unsupervised approaches (TF.IDF, KP-Miner, RAKE, TextRank, SingleRank, ExpandRank, 
    TopicRank, TopicalPageRank, PositionRank and MultipartiteRank), and one supervised method (KEA). 
    Experimental results carried out on top of twenty datasets (see Benchmark section below) show that 
    our methods significantly outperform state-of-the-art methods under a number of collections of 
    different sizes, languages or domains. In addition to the python package here described, we also 
    make available a demo, an API and a mobile app.
  doc_url: https://github.com/LIAAD/yake
  dev_url: https://github.com/LIAAD/yake
extra:
  recipe-maintainers:
    - primozgodec
